language: ruby

node_js:
  - "8"

addons:
  firefox: "latest"

cache: bundler

rvm:
  - 2.5

install:
  - bundle install --path vendor/bundle
  - bundle update rubocop
  - npm install -g ember-cli
  - npm i -g npm
  - npm --prefix ./frontend install ./frontend

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:setup

services:
  - xvfb
  - postgresql

script:
  - bundle --deployment
  - JOBS=1 bundle exec rake ci
