categories:
  Beratung:
    - Digital Consulting
    - Tech Consulting
    - Open Source Consulting
  UX Design:
    - UX Methoden
    - UX Tools
  Software Engineering:
    - Java
    - Ruby
    - Frontend
    - Multiplatform Apps
    - Web- & Application Server
    - Streaming & Messaging
    - DB / DB-Server
    - AI & ML
    - API Mgmt & Microservices
  Architektur & Design:
    - Software Design
    - Software Architektur
  Delivery:
    - CI/CD
    - Container Platform / PaaS
    - Container Engineering
  System Engineering:
    - Cloud Management
    - Config & Workflow Mgmt
    - Virtualisierung
    - Hochverfügbarkeit
    - Linux Engineering
    - Security & Auth
    - Neworking
    - Packaging
    - Backup Services
    - Mail Service
  Diverses:
    - Sprachen
    - Tools
    - Vorgehensmethoden
    - Ohne Kategorien

radar:
  - adopt
  - trial
  - assess
  - hold

portfolio:
  - aktiv
  - passiv
  - abbauen
